# Generated by Django 3.2.8 on 2021-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='progress_percent',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='progress_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_percent',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='progress_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='target_score',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
