# Generated by Django 3.2.8 on 2021-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20211208_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
