# Generated by Django 3.2.10 on 2021-12-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_course_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='term',
            new_name='order',
        ),
    ]
