# Generated by Django 3.2.10 on 2021-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_rename_term_semester_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
